# Generated by Django 5.2.12 on 2026-03-18 23:43

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email invitado')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token UUID (legacy)')),
                ('token_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash HMAC del token de activación')),
                ('token_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Token creado el')),
                ('is_used', models.BooleanField(default=False, verbose_name='Usada')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de uso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expira el')),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_received', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creado')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por')),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
            },
        ),
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Hash del token')),
                ('email', models.EmailField(max_length=254, verbose_name='Email invitado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Usado el')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por')),
            ],
            options={
                'verbose_name': 'Token de invitación',
                'verbose_name_plural': 'Tokens de invitación',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash del token')),
                ('expires_at', models.DateTimeField(verbose_name='Expira el')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Usado el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de reseteo de contraseña',
                'verbose_name_plural': 'Tokens de reseteo de contraseña',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Tu identidad pública. Nadie verá tu email.', max_length=50, unique=True, verbose_name='Nickname')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografía')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[accounts.models.validate_avatar], verbose_name='Avatar')),
                ('comment_allowance_depth', models.IntegerField(default=2, help_text='Niveles hacia arriba (invitadores) y abajo (invitados) habilitados para comentar en tus highlights públicos.', verbose_name='Niveles permitidos para comentar')),
                ('is_hermit_mode', models.BooleanField(default=False, help_text='Si está activado, tu perfil público y tus highlights públicos no son visibles para terceros.', verbose_name='Modo Ermitaño')),
                ('is_discoverable', models.BooleanField(default=True, help_text='Si está desactivado, no aparecés en sugerencias del feed ni verás la sección de descubrimiento.', verbose_name='Aparecer en feed de descubrimiento')),
                ('verified_email', models.EmailField(help_text='Solo para admin/soporte. Nunca público.', max_length=254, verbose_name='Email verificado')),
                ('full_name', models.CharField(blank=True, help_text='Solo para admin/soporte. Nunca público.', max_length=100, verbose_name='Nombre completo')),
                ('onboarding_completed', models.BooleanField(default=False, verbose_name='Onboarding completado')),
                ('must_change_credentials', models.BooleanField(default=False, help_text='Si está activo, el usuario debe definir nickname y contraseña propios.', verbose_name='Debe cambiar credenciales')),
                ('discovery_activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Discovery activado el')),
                ('trust_promoted_at', models.DateTimeField(blank=True, help_text='Fecha en que el sistema promovió automáticamente el nivel de confianza del usuario.', null=True, verbose_name='Confianza promovida el')),
                ('invitation_depth', models.IntegerField(default=0, help_text='0 = genesis/superuser. Calculado al crear el perfil.', verbose_name='Profundidad en árbol de invitaciones')),
                ('goodreads_username', models.CharField(blank=True, help_text='Opcional. Tu nombre de usuario en Goodreads.', max_length=100, verbose_name='Usuario de Goodreads')),
                ('goodreads_feed_url', models.URLField(blank=True, verbose_name='URL de Goodreads RSS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_created', to='accounts.invitation', verbose_name='Invitación usada')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('message', models.TextField(blank=True, help_text='Opcional. Contexto para quien decida activar la cuenta.', max_length=500, verbose_name='Por qué quiero unirme')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado el')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Activado el')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Activado')),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_activations', to='accounts.profile', verbose_name='Activado por')),
            ],
            options={
                'verbose_name': 'Lista de espera',
                'verbose_name_plural': 'Lista de espera',
                'ordering': ['requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['email'], name='accounts_in_email_571f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['token'], name='accounts_in_token_be8e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['invited_by', 'is_used'], name='accounts_in_invited_e0784f_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationtoken',
            index=models.Index(fields=['email', 'invited_by'], name='accounts_in_email_dce047_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationtoken',
            index=models.Index(fields=['created_at'], name='accounts_in_created_3f0569_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'created_at'], name='accounts_pa_user_id_8cd138_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['expires_at'], name='accounts_pa_expires_01b447_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['nickname'], name='accounts_pr_nicknam_3aefb5_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['email'], name='accounts_wa_email_fc9163_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['is_activated', 'requested_at'], name='accounts_wa_is_acti_c2e285_idx'),
        ),
    ]
