# Generated by Django 5.2.12 on 2026-03-18 23:43

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reading', 'Leyendo'), ('finished', 'Terminado'), ('abandoned', 'Abandonado')], default='reading', max_length=10, verbose_name='Estado')),
                ('progress', models.FloatField(default=0.0, help_text='0.0 a 1.0', verbose_name='Progreso (%)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='books.book', verbose_name='Libro')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='accounts.profile', verbose_name='Lector')),
            ],
            options={
                'verbose_name': 'Sesión de Lectura',
                'verbose_name_plural': 'Sesiones de Lectura',
                'indexes': [models.Index(fields=['profile', 'status'], name='affinity_re_profile_2fcd20_idx'), models.Index(fields=['book', 'status'], name='affinity_re_book_id_4d426d_idx')],
                'unique_together': {('profile', 'book')},
            },
        ),
        migrations.CreateModel(
            name='UserCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroid', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True, verbose_name='Centroide')),
                ('cluster_label', models.IntegerField(blank=True, help_text='Grupo asignado por K-Means', null=True, verbose_name='Etiqueta de cluster')),
                ('highlights_count', models.IntegerField(default=0, verbose_name='Cantidad de highlights usados')),
                ('last_computed', models.DateTimeField(blank=True, null=True, verbose_name='Último cálculo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='accounts.profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Cluster de Usuario',
                'verbose_name_plural': 'Clusters de Usuarios',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['centroid'], m=16, name='usercluster_centroid_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
