# Generated by Django 5.2.12 on 2026-03-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('content', models.TextField(help_text='Formato Markdown. Se renderiza en el frontend.', verbose_name='Contenido (Markdown)')),
                ('placement', models.CharField(choices=[('onboarding', 'Onboarding / Footer'), ('discovery', 'Sugerencias de Red'), ('comments', 'Panel de Comentarios'), ('import', 'Importación de Goodreads')], max_length=20, verbose_name='Ubicación en la UI')),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición dentro de su placement', verbose_name='Orden')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artículo Ético',
                'verbose_name_plural': 'Artículos Éticos',
                'ordering': ['placement', 'order'],
            },
        ),
    ]
