# Generated by Django 5.2.12 on 2026-03-18 23:43

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('openlibrary_id', models.CharField(blank=True, max_length=100, verbose_name='ID de OpenLibrary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='books_autho_name_5aec2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Portada')),
                ('openlibrary_id', models.CharField(blank=True, max_length=100, verbose_name='ID de OpenLibrary')),
                ('average_rating', models.FloatField(blank=True, null=True, verbose_name='Calificación promedio')),
                ('publish_year', models.IntegerField(blank=True, null=True, verbose_name='Año de publicación')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Género')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='books', to='books.author', verbose_name='Autores')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('note', models.TextField(blank=True, verbose_name='Nota personal')),
                ('location', models.CharField(max_length=50, verbose_name='Ubicación')),
                ('visibility', models.CharField(choices=[('private', 'Privado'), ('unlisted', 'Oculto'), ('public', 'Público')], default='private', max_length=10, verbose_name='Visibilidad')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de importación')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Highlight',
                'verbose_name_plural': 'Highlights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Contenido')),
                ('visibility', models.CharField(choices=[('private', 'Privado'), ('unlisted', 'Oculto'), ('public', 'Público')], default='private', max_length=10, verbose_name='Visibilidad')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='books_book_title_d3218d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='books_book_isbn_54becd_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['user', 'visibility'], name='books_highl_user_id_473340_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['book'], name='books_highl_book_id_9c3805_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['created_at'], name='books_highl_created_4cf0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='highlight_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'visibility'], name='books_note_user_id_3422b6_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_at'], name='books_note_created_70b61a_idx'),
        ),
    ]
