# Generated by Django 5.2.12 on 2026-03-18 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_book_title', models.CharField(blank=True, help_text='Título del libro que dio origen al hilo, si aplica.', max_length=500, verbose_name='Libro de contexto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Último mensaje el')),
                ('participants', models.ManyToManyField(related_name='threads', to='accounts.profile', verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Hilo',
                'verbose_name_plural': 'Hilos',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Máximo 2000 caracteres. Sin markdown.', max_length=2000, verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado el')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='accounts.profile', verbose_name='Autor')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='threads.thread', verbose_name='Hilo')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['thread', 'created_at'], name='threads_thr_thread__5c5715_idx')],
            },
        ),
    ]
