# Generated by Django 5.2.12 on 2026-03-18 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Máximo 1000 caracteres. Sin markdown.', max_length=1000, verbose_name='Contenido')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de moderación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10, verbose_name='Estado de moderación')),
                ('toxicity_score', models.FloatField(default=0.0, help_text='0.0 = seguro, 1.0 = tóxico', verbose_name='Score de toxicidad')),
                ('moderation_reason', models.CharField(blank=True, max_length=255, verbose_name='Razón de moderación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.profile', verbose_name='Autor')),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.highlight', verbose_name='Highlight')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['highlight', 'status'], name='social_comm_highlig_d4257d_idx'), models.Index(fields=['author'], name='social_comm_author__29a094_idx'), models.Index(fields=['status', 'created_at'], name='social_comm_status_348dba_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='accounts.profile', verbose_name='Seguidor')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='accounts.profile', verbose_name='Siguiendo a')),
            ],
            options={
                'verbose_name': 'Seguidor',
                'verbose_name_plural': 'Seguidores',
                'indexes': [models.Index(fields=['follower', 'following'], name='social_user_followe_89c161_idx'), models.Index(fields=['following'], name='social_user_followi_2783cd_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
